<?php

namespace Product\Property\Classes;

use App\Product\Property\Classes\PropertyCollector;
use PHPUnit\Framework\TestCase;

class PropertyCollectorTest extends TestCase
{
    private PropertyCollector $propertyCollector;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->propertyCollector = new PropertyCollector();
    }

    public function testGetPropertiesForValues()
    {

    }

    public function testCollectByProductId()
    {

    }
}
